### PR TITLE
Update ReplaceTokens task to v5 to fix node version error in build. Minor spelling/typo fix.

### PR DESCRIPTION
**Pull request by jameswiseman76**
To fix the build error currently happening on the ADO pipeline.

Using this:
https://github.com/qetza/vsts-replacetokens-task/blob/master/tasks/ReplaceTokensV5/task.json

Also fixes a minor typo on the .md displayed on the VS Extensions Gallery.

### CODE REVIEW

**Comment by rouke-broersma** [comment]
Could you also update the tfx tasks to a more recent version 😁😅

**Comment by jameswiseman76** [comment]
@rouke-broersma Do you have a version in mind?

**Comment by rouke-broersma** [comment]
@4?

**Comment by jameswiseman76** [comment]
Sure. this? https://github.com/microsoft/azure-devops-extension-tasks/tree/main/BuildTasks/TfxInstaller/v4

**Comment by jameswiseman76** [comment]
@rouke-broersma. There you go 

          - task: TfxInstaller@4

**Comment by rouke-broersma** [comment]
You can see the build here: https://dev.azure.com/stryker-mutator/Stryker/_build?definitionId=10 there are a couple more out of date tasks. If you could fix them that would be great! No worries if you don't have time, in that case I'll do it when I'm back home.

**Comment by rouke-broersma** [comment]
Thank you!

**Comment by rouke-broersma** [comment]
It's already merged

**Comment by jameswiseman76** [comment]
Great. Does something need to happen here though? 
https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=14551&view=logs&j=70449add-7425-5c45-f1a3-67b12442f474

The build on here is still showing as failed too, presumably because the PRD deploy needs to finish?

**Comment by rouke-broersma** [comment]
Not sure what you mean, the new builds are showing as passed

**Comment by jameswiseman76** [comment]
image

Say's PRD deploy is 'Pending'

**Comment by rouke-broersma** [comment]
Yes, I haven't approved a production deployment. There isn't really any need is there? Or did I forget to release something?

**Comment by jameswiseman76** [comment]
I see the bot update is breaking as well. 

https://dev.azure.com/stryker-mutator/Stryker/_build/results?buildId=14562&view=logs&j=0c080714-50ff-5eb5-8403-7c78be40ecf7&t=86b7d056-28db-5367-82b5-008d45640a42

Is that because it's pulled in a new package version that requires a new package.json dependency?

**Comment by rouke-broersma** [comment]
> I'm not sure how it works in practice, but I had assumed that the PRD release deploys to the Marketplace?
> 
> https://marketplace.visualstudio.com/items?itemName=stryker-mutator.mutation-report-publisher
> 
> Also, what updates the pipeline build status?
> 
> image
> 
> 

That is correct. The failing badge will remain until a release is done.

**Comment by jameswiseman76** [comment]
Sure, ok.

I may take a look tomorrow, though.  My company has fairly stringent
controls around bringing these things into our ADO, and I think this will
be a showstopper.

I work for a famly large UK financial services company,  and this is the
last step in rolling stryker out to 100+ devs. Pretty excited about it

**Comment by jameswiseman76** [comment]
Thanks! I'll check with them tomorrow.

They're really good guys, and it may be enough to know that's its well
engaged and has a community&team right in top of it.

Fixing both will definitely help,  though.

James

**Pull request merged**
