### PR TITLE
feat: Support multiple reports in the same pipeline

### PR DESCRIPTION
**Pull request by leonardosimoura**
This is a very fast and simple solution to enable multiple reports

i dont know how to test it in a real pipeline on Azure Dev Ops, soo a made some mocks for see the changes ...

The results will be something like this
image

I named the reports like mutation-report-1,mutation-report-2, etc

If there is a suggestion or anything to improve, please let me know.

### CODE REVIEW

**Comment by rouke-broersma** [comment]
Wow awesome! 😄😄

I'll test this when I can!

**Comment by rouke-broersma** [comment]
image

🎉🎉🎉🎉🎉🎉🎉

**Comment by philip-reed** [comment]
Is there any way to control the names of the reports instead of using `mutation-report-1.html` etc.
If there is a file name defined in the stryker-config.json, could this use the name defined there for the tabs along the top?

**Comment by rouke-broersma** [comment]
@philip-reed there already is an option to give a custom name to the report.

**Comment by philip-reed** [comment]
@rouke-broersma Yes, there is, I hadn't set the new flag to use the Stryker report name.

Nice work!

image

**Pull request merged**
