### PR TITLE
Fix #176 "Report tab not loading on ADO"

### LINKED ISSUE #176: Report tab not loading on Azure devops server
I'm attempting to use this plugin on our Azure devops server but the report tab seems to be infinitely loading when I open it.
I have included my Yaml pipeline (Stryker is running with correct output and the file is generated) and some logs from the Chrome Developers Console. This last one seems to contain an error.

### Versions
 - dotnet-stryker: 0.20.0
 - azure-devops-mutationreport-publisher: 0.1.3

### Yaml

```
- task: DotNetCoreCLI@2
    displayName: 'Install dotnet-stryker'
    inputs:
      command: custom
      custom: tool
      arguments: update dotnet-stryker --tool-path $(Agent.ToolsDirectory)

  - task: Powershell@2
    displayName: 'Run mutation test on ${{ parameters.testName}}'
    inputs:
      workingDirectory: ${{ parameters.workingDirectory }}
      targetType: 'inline'
      script: $(Agent.ToolsDirectory)/dotnet-stryker ${{ parameters.strykerCommands}}

  - task: PublishMutationReport@0
    displayName: 'Publish Mutation Test Report'
    inputs:
      reportPattern: '**/mutation-report.html'
```

### Developer console
image

I can confirm, by using the diagnostic logs, that the html file is found and uploaded by the task.

### PR DESCRIPTION
**Pull request by xakep139**
This PR fixes #176

### CODE REVIEW

**Comment by rouke-broersma** [comment]
Hi 👋

I tested your solution but unfortunately this bug is not fixed: https://github.com/microsoft/azure-devops-extension-api/issues/36

getBuildPageData returns a Promise but the interface specified that it is a synchronous call:

image

At the same time the getConfiguration solution still works fine on azure devops cloud, it just doesn't work in azure devops server.

**Comment by rouke-broersma** [comment]
@xakep139 I modified your pr by adding the missing await and it seems to be working in my testing! Would you perhaps be available to test the extension within your context? If it's azure devops server I can provide you with the vsix and if it's azure devops cloud I can share the 'test' package with you if you give me your azure devops org name.

Or perhaps @psfinaki?

**Comment by xakep139** [comment]
@rouke-broersma many thanks for your testing and fix!
Hey @psfinaki, can we test it using either of these two options?

**Comment by psfinaki** [comment]
@xakep139 awesome job! 

@rouke-broersma thanks for the brief response and fix :) I'm not exactly what is meant by "Azure DevOps Cloud" but I guess we can start with the vsix extension. I hope I will be able to test it early next week, depends on bureaucracy in the company.

**Comment by rouke-broersma** [comment]
Azure devops cloud as in not server so https://dev.azure.com

**Comment by psfinaki** [comment]
Thanks! Will give you an update on that asap :)

**Comment by psfinaki** [comment]
Hey @rouke-broersma 

Okay so I got the point, vsix is not an option, I don't see a way to upload a custom vsix to ADO so that a pipeline can use it.

As for the second way, yeah so I'm not sure if I am allowed to share the name of the ADO org - but if I am, how the process is going to look like?

I guess a lame way would be to just release this version and see if it works, updating the extension shouldn't be an issue. I mean, usually it's not the best way to go, but given that the extension has just about 100+ installs and is not working anyway, maybe you would consider that.

**Comment by rouke-broersma** [comment]
> Hey @rouke-broersma
> 
> Okay so I got the point, vsix is not an option, I don't see a way to upload a custom vsix to ADO so that a pipeline can use it.
> 
> As for the second way, yeah so I'm not sure if I am allowed to share the name of the ADO org - but if I am, how the process is going to look like?
> 

I have a private extension published with the test version, I can 'share' this extension with your org from the marketplace by putting in the org name. Then you will have a new extension on the 'Shared' tab on the extensions page in your org and you can install the test extension.

> I guess a lame way would be to just release this version and see if it works, updating the extension shouldn't be an issue. I mean, usually it's not the best way to go, but given that the extension has just about 100+ installs and is not working anyway, maybe you would consider that.

The extension does work in other orgs. So far your org is the only azure devops cloud org where the extension does not work. If you check the bug report they are talking about azure devops server where it's not working.

Since from my tests the new solution does work I could just release a new version with this fix but if at all possible I would like to confirm that this actually fixes the issue for you since I personally don't have any reproduction (because the extension works fine in all my orgs).

**Comment by psfinaki** [comment]
@rouke-broersma okay, so I made a round of privacy consultations, and the org name is "domoreexp" 🤦

**Comment by rouke-broersma** [comment]
> @rouke-broersma okay, so I made a round of privacy consultations, and the org name is "domoreexp" 🤦

Awesome! I have shared the extension with your org now. It should show up here: https://dev.azure.com/domoreexp/_settings/extensions?tab=shared

Unfortunately you will have to temporarily uninstall the public version I think because of naming conflicts between the public and private version.

**Comment by psfinaki** [comment]
Okay I can see the extension in that tab, I will do further bureaucracy and then come back to you :)

**Comment by psfinaki** [comment]
Gosh, that's taking a while. 

@rouke-broersma, just a quick check - is it possible to publish and share this version with a different name (e.g. adding `Test` suffix) to avoid the name collision?

I know that's all ridiculous, but, you know, large org, supply chain attack paranoia and all that stuff.

**Comment by rouke-broersma** [comment]
> Gosh, that's taking a while.
> 
> @rouke-broersma, just a quick check - is it possible to publish and share this version with a different name (e.g. adding `Test` suffix) to avoid the name collision?
> 
> I know that's all ridiculous, but, you know, large org, supply chain attack paranoia and all that stuff.

It's already published with a different name, the issue is the task ID. The ID is auto generated based on a few constants and somewhere along the lines something went wrong with the auto generation or the deployment so the production released task now has the ID that's normally generated for test.. I dunno. I can try to fix this tonight.

Perfectly understandable that you wouldn't want to just randomly install extensions I get it.

**Comment by rouke-broersma** [comment]
Ya know what how about I just merge this anyway since it works for in my tests 🤷 I don't want to put you through any more hassle either.

**Comment by psfinaki** [comment]
Well that would be very nice of you and should save some time :)

**Comment by rouke-broersma** [comment]
3-2-1 🤞🤞🤞

**Comment by psfinaki** [comment]
Thanks :) should the CI provide the new version? Currently the build seems to be failing for some reason.

**Comment by rouke-broersma** [comment]
Yea that was my bad, it's been so long I forgot I have to update the version number. It's been released now.

**Comment by psfinaki** [comment]
Great, yes, I see it now. Trying things out, fingers crossed!

**Comment by psfinaki** [comment]
Well... not working, but the error has changed :D I will reopen the issue :)

**Pull request merged**
